"""Vision tool — describe an image so Theo can "see" it.

Theo's brain (the claude CLI in -p mode) isn't multimodal-native in
our setup; we shell out to it for text. So vision becomes a tool:
Theo calls describe_image(url) on an image he wants to understand,
gets a structured description back, and reasons about it.

Two backends, tried in order:

  1. Ollama + a local vision model (llava / llama3.2-vision / etc).
     Free, local, no API key. Requires Ollama installed and the
     vision model pulled:
         ollama pull llama3.2-vision

  2. Failure path — return a clear error with install instructions.
     We deliberately don't fall back to a paid API; that's Ian's
     "no per-token charges" rule.

Use cases:
  - Ian pastes an image URL: "what's in this image?"
  - Theo wants to verify a Pollinations generation matches the prompt.
  - QR code introspection (Theo can scan QRs by describing them)."""
from __future__ import annotations

import base64
import os
import shutil
import subprocess
import tempfile
from io import BytesIO
from pathlib import Path
from typing import Any

from .base import Tool


DEFAULT_VISION_MODEL = "llama3.2-vision"


def _fetch_image(url_or_path: str) -> bytes | None:
    src = url_or_path.strip()
    if not src:
        return None
    try:
        if src.startswith(("http://", "https://")):
            try:
                import requests
            except ImportError:
                return None
            r = requests.get(src, timeout=20)
            if r.status_code >= 400:
                return None
            return r.content
        if src.startswith("data:"):
            comma = src.find(",")
            if comma < 0:
                return None
            return base64.b64decode(src[comma + 1:])
        p = Path(src).expanduser()
        if p.exists():
            return p.read_bytes()
    except Exception:
        return None
    return None


def _ollama_available() -> bool:
    return shutil.which("ollama") is not None


def _describe_via_ollama(image_bytes: bytes,
                         prompt: str,
                         model: str) -> dict[str, Any]:
    """Use ollama's CLI to describe the image. Cheap and local."""
    fd, path = tempfile.mkstemp(suffix=".png", prefix="theo_vis_")
    os.close(fd)
    Path(path).write_bytes(image_bytes)
    try:
        # Newer Ollama supports `ollama run <model> "prompt" --image path`.
        # Older versions accept stdin with a multimodal message; we try
        # the modern path first.
        cmd = ["ollama", "run", model, prompt, "--image", path]
        try:
            proc = subprocess.run(
                cmd, capture_output=True, text=True, timeout=90,
                encoding="utf-8", errors="replace",
            )
        except subprocess.TimeoutExpired:
            return {"error": f"ollama vision timed out (model={model})"}
        if proc.returncode != 0:
            return {
                "error": f"ollama exit {proc.returncode}",
                "stderr": (proc.stderr or "")[:400],
                "hint": (
                    f"Make sure the vision model is pulled: "
                    f"`ollama pull {model}`. If your Ollama version is "
                    f"older, the --image flag may not be supported; "
                    f"upgrade Ollama."
                ),
            }
        return {
            "backend":     "ollama",
            "model":       model,
            "description": (proc.stdout or "").strip(),
        }
    finally:
        try:
            Path(path).unlink()
        except Exception:
            pass


def _describe_image(source: str,
                     prompt: str = "Describe this image in concrete detail. What's in it, what's the composition, what stands out?",
                     model: str | None = None) -> dict[str, Any]:
    """Describe an image at a URL, data URI, or local path."""
    img = _fetch_image(source)
    if img is None:
        return {"error": f"could not fetch image from {source!r}"}

    if not _ollama_available():
        return {
            "error": "no vision backend available",
            "fix": (
                "Install Ollama (https://ollama.com) and pull a vision "
                "model: `ollama pull llama3.2-vision`. Theo's text "
                "brain (claude CLI) isn't multimodal in this setup, so "
                "vision goes through a local Ollama model."
            ),
        }

    chosen_model = model or os.environ.get("THEO_VISION_MODEL") or DEFAULT_VISION_MODEL
    return _describe_via_ollama(img, prompt, chosen_model)


DESCRIBE_IMAGE_TOOL = Tool(
    name="describe_image",
    description=(
        "See what's in an image. Pass `source` as a URL (http/https), "
        "a data: URI, or a local file path. Returns a description "
        "generated by a local vision model (Ollama + llama3.2-vision "
        "by default). Use this when the human shares an image URL "
        "and asks about it, when you want to verify a generated image "
        "matches the prompt, or when you need to read text inside an "
        "image (like a screenshot). Requires Ollama installed locally; "
        "graceful error with install instructions otherwise."
    ),
    parameters_schema={
        "type": "object",
        "properties": {
            "source": {"type": "string", "description": "Image URL, data URI, or local file path."},
            "prompt": {
                "type": "string",
                "description": (
                    "What to ask the vision model. Default is a generic "
                    "describe; override for specific questions like "
                    "'what does the sign say?' or 'what color is the car?'."
                ),
            },
            "model": {
                "type": "string",
                "description": (
                    "Ollama vision model name. Default 'llama3.2-vision'. "
                    "Override via env var THEO_VISION_MODEL or this arg."
                ),
            },
        },
        "required": ["source"],
        "additionalProperties": False,
    },
    handler=_describe_image,
)


def register(registry) -> None:
    registry.register(DESCRIBE_IMAGE_TOOL)
